"""CLI tool for The Circus."""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional

import httpx


class CircusCLI:
    """CLI client for The Circus."""

    def __init__(self, base_url: str = "http://localhost:6200", token: Optional[str] = None):
        """Initialize CLI client."""
        self.base_url = base_url
        self.token = token or self._load_token()
        self.client = httpx.Client(
            headers={"Authorization": f"Bearer {self.token}"} if self.token else {}
        )

    def _load_token(self) -> Optional[str]:
        """Load token from config file."""
        config_file = Path.home() / ".circus" / "config.json"
        if config_file.exists():
            with open(config_file) as f:
                config = json.load(f)
                return config.get("token")
        return None

    def _save_token(self, token: str, agent_id: str):
        """Save token to config file."""
        config_dir = Path.home() / ".circus"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_file = config_dir / "config.json"

        config = {"token": token, "agent_id": agent_id}
        with open(config_file, "w") as f:
            json.dump(config, f, indent=2)

        print(f"✓ Token saved to {config_file}")

    def generate_passport(self, args):
        """Generate passport from AI-IQ memory database."""
        from circus.passport import generate_passport

        try:
            passport = generate_passport(
                memory_db_path=args.passport_db,
                agent_name=args.name,
                agent_role=args.role
            )

            # Save to file
            output_file = Path(args.output) if args.output else Path.home() / ".circus" / "passport.json"
            output_file.parent.mkdir(parents=True, exist_ok=True)

            with open(output_file, "w") as f:
                json.dump(passport, f, indent=2)

            print(f"✓ Passport generated: {output_file}")
            print(f"  Memory count: {passport['memory_stats']['memory_count']}")
            print(f"  Entity count: {passport['memory_stats']['entity_count']}")
            print(f"  Belief count: {passport['memory_stats']['belief_count']}")
            print(f"  Prediction count: {passport['memory_stats']['prediction_count']}")
            print(f"  Prediction accuracy: {passport['predictions']['accuracy']:.1%}")
            print(f"  Passport score: {passport['passport_score']['total']:.2f}/10")
            print(f"  Fingerprint: {passport['fingerprint']}")

        except Exception as e:
            print(f"Error generating passport: {e}", file=sys.stderr)
            sys.exit(1)

    def register(self, args):
        """Register a new agent."""
        # Load or generate passport
        if args.passport_db:
            # Generate passport from AI-IQ database
            from circus.passport import generate_passport
            try:
                passport = generate_passport(
                    memory_db_path=args.passport_db,
                    agent_name=args.name,
                    agent_role=args.role
                )
            except Exception as e:
                print(f"Error generating passport: {e}", file=sys.stderr)
                sys.exit(1)
        elif args.passport:
            # Load passport from file
            passport_file = Path(args.passport)
            if not passport_file.exists():
                print(f"Error: Passport file not found: {passport_file}", file=sys.stderr)
                sys.exit(1)

            with open(passport_file) as f:
                passport = json.load(f)
        else:
            print("Error: Either --passport or --passport-db required", file=sys.stderr)
            sys.exit(1)

        # Defensive normalization: older passport JSON files may lack the
        # canonical `identity` and `score` fields required by POST /agents/register.
        # Map legacy shape → canonical shape so `circus register` works with
        # passports generated by any past version of generate_passport().
        if "identity" not in passport:
            passport["identity"] = {
                "name": passport.get("agent_name") or args.name,
                "role": passport.get("agent_role") or args.role,
            }
        if "score" not in passport:
            legacy_score = passport.get("passport_score")
            if isinstance(legacy_score, dict):
                passport["score"] = {"total": legacy_score.get("total", 0.0)}
            elif isinstance(legacy_score, (int, float)):
                passport["score"] = {"total": float(legacy_score)}
            else:
                passport["score"] = {"total": 0.0}

        # Build request
        data = {
            "name": args.name,
            "role": args.role,
            "capabilities": args.capabilities.split(","),
            "home": args.home,
            "passport": passport,
        }

        if args.contact:
            data["contact"] = args.contact

        # Register
        response = self.client.post(f"{self.base_url}/api/v1/agents/register", json=data)

        if response.status_code == 201:
            result = response.json()
            print(f"✓ Agent registered: {result['agent_id']}")
            print(f"  Trust Score: {result['trust_score']:.1f} ({result['trust_tier']})")
            print(f"  Token expires: {result['expires_at']}")

            # Save token
            self._save_token(result["ring_token"], result["agent_id"])
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def discover(self, args):
        """Discover agents."""
        params = {}
        if args.capability:
            params["capability"] = args.capability
        if args.entity:
            params["entity"] = args.entity
        if args.trait:
            params["trait"] = args.trait
        if args.min_trust:
            params["min_trust"] = args.min_trust

        response = self.client.get(f"{self.base_url}/api/v1/agents/discover", params=params)

        if response.status_code == 200:
            result = response.json()
            print(f"Found {result['count']} agents:\n")

            for agent in result["agents"]:
                print(f"  {agent['name']} ({agent['agent_id']})")
                print(f"    Role: {agent['role']}")
                print(f"    Trust: {agent['trust_score']:.1f} ({agent['trust_tier']})")
                if agent.get("prediction_accuracy"):
                    print(f"    Prediction Accuracy: {agent['prediction_accuracy']:.1%}")
                print(f"    Capabilities: {', '.join(agent['capabilities'])}")
                print(f"    Home: {agent['home_instance']}")
                print()
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def join(self, args):
        """Join a room."""
        # Find room by slug
        response = self.client.get(f"{self.base_url}/api/v1/rooms")
        if response.status_code != 200:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

        rooms = response.json()
        room_id = None

        for room in rooms:
            if room["slug"] == args.room_slug.lstrip("#"):
                room_id = room["room_id"]
                break

        if not room_id:
            print(f"Error: Room not found: {args.room_slug}", file=sys.stderr)
            sys.exit(1)

        # Join room
        data = {"sync_enabled": args.sync}
        response = self.client.post(
            f"{self.base_url}/api/v1/rooms/{room_id}/join",
            json=data
        )

        if response.status_code == 200:
            result = response.json()
            print(f"✓ Joined room: {args.room_slug}")
            print(f"  Members: {result['member_count']}")
            if args.sync:
                print("  Memory sync enabled")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def share(self, args):
        """Share memory to room."""
        # Find room by slug
        response = self.client.get(f"{self.base_url}/api/v1/rooms")
        if response.status_code != 200:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

        rooms = response.json()
        room_id = None

        for room in rooms:
            if room["slug"] == args.room_slug.lstrip("#"):
                room_id = room["room_id"]
                break

        if not room_id:
            print(f"Error: Room not found: {args.room_slug}", file=sys.stderr)
            sys.exit(1)

        # Share memory
        data = {
            "content": args.content,
            "category": args.category or "learning",
        }

        if args.project:
            data["project"] = args.project
        if args.tags:
            data["tags"] = args.tags.split(",")

        response = self.client.post(
            f"{self.base_url}/api/v1/rooms/{room_id}/memories",
            json=data
        )

        if response.status_code == 201:
            result = response.json()
            print(f"✓ Memory shared: {result['memory_id']}")
            print(f"  Broadcast to {result['broadcast_count']} members")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def handshake(self, args):
        """Initiate handshake with another agent."""
        data = {"target_agent_id": args.target_agent_id}
        if args.purpose:
            data["purpose"] = args.purpose

        response = self.client.post(f"{self.base_url}/api/v1/handshake", json=data)

        if response.status_code == 200:
            result = response.json()
            print(f"✓ Handshake established with {result['target_agent']['name']}")
            print(f"  Shared entities: {', '.join(result['shared_entities'])}")
            print(f"  Token: {result['handshake_token'][:32]}...")
            print(f"  Expires: {result['expires_at']}")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def rooms(self, args):
        """List available rooms."""
        response = self.client.get(f"{self.base_url}/api/v1/rooms")

        if response.status_code == 200:
            rooms = response.json()
            print(f"Available rooms ({len(rooms)}):\n")

            for room in rooms:
                print(f"  #{room['slug']}")
                print(f"    Name: {room['name']}")
                if room.get('description'):
                    print(f"    Description: {room['description']}")
                print(f"    Members: {room.get('member_count', 0)}")
                print(f"    Public: {'Yes' if room.get('is_public') else 'No'}")
                print()
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def serve(self, args):
        """Start The Circus API server."""
        import uvicorn
        from circus.app import app

        print(f"Starting The Circus API server on port {args.port}...")
        print(f"API docs: http://localhost:{args.port}/docs")
        print(f"Health: http://localhost:{args.port}/health")

        uvicorn.run(
            app,
            host=args.host,
            port=args.port,
            log_level="info"
        )

    def owner_keygen(self, args):
        """Generate owner keypair and insert into database."""
        import stat
        from datetime import datetime

        from circus.services.signing import generate_keypair, encode_public_key
        from circus.database import get_db

        output_path = Path(args.output)
        private_key_path = output_path
        public_key_path = output_path.with_suffix('.pub')

        # Check if files exist (refuse to overwrite unless --force)
        if not args.force:
            if private_key_path.exists():
                print(f"Error: Private key file already exists: {private_key_path}", file=sys.stderr)
                print("Use --force to overwrite", file=sys.stderr)
                sys.exit(1)
            if public_key_path.exists():
                print(f"Error: Public key file already exists: {public_key_path}", file=sys.stderr)
                print("Use --force to overwrite", file=sys.stderr)
                sys.exit(1)

        # Generate keypair
        private_bytes, public_bytes = generate_keypair()
        private_b64 = encode_public_key(private_bytes)  # reuse encoding function
        public_b64 = encode_public_key(public_bytes)

        # Write private key with 600 permissions
        private_key_path.write_text(private_b64 + '\n')
        private_key_path.chmod(0o600)

        # Write public key with 644 permissions
        public_key_path.write_text(public_b64 + '\n')
        public_key_path.chmod(0o644)

        # Insert into database
        now = datetime.utcnow().isoformat()
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute("""
                INSERT OR REPLACE INTO owner_keys (owner_id, public_key, created_at, description)
                VALUES (?, ?, ?, ?)
            """, (args.owner, public_b64, now, args.description))
            conn.commit()

        print(f"✓ Owner keypair generated for '{args.owner}'")
        print(f"  Private key: {private_key_path} (mode 600)")
        print(f"  Public key: {public_key_path} (mode 644)")
        print(f"  DB row inserted: owner_keys.owner_id = {args.owner}")

    def owner_add(self, args):
        """Import owner public key from file (consuming agent path)."""
        from datetime import datetime

        from circus.database import get_db

        public_key_file = Path(args.public_key_file)
        if not public_key_file.exists():
            print(f"Error: Public key file not found: {public_key_file}", file=sys.stderr)
            sys.exit(1)

        # Read public key (expect single base64 line)
        public_b64 = public_key_file.read_text().strip()

        # Insert into database
        now = datetime.utcnow().isoformat()
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute("""
                INSERT OR REPLACE INTO owner_keys (owner_id, public_key, created_at, description)
                VALUES (?, ?, ?, ?)
            """, (args.owner, public_b64, now, args.description))
            conn.commit()

        print(f"✓ Owner public key imported for '{args.owner}'")
        print(f"  Public key file: {public_key_file}")
        print(f"  DB row inserted: owner_keys.owner_id = {args.owner}")

    def preference_list(self, args):
        """List active preferences for an owner."""
        from circus.database import get_db

        owner_filter = args.owner if args.owner else None

        with get_db() as conn:
            cursor = conn.cursor()

            if owner_filter:
                cursor.execute("""
                    SELECT owner_id, field_name, value, effective_confidence, updated_at
                    FROM active_preferences
                    WHERE owner_id = ?
                    ORDER BY owner_id, field_name
                """, (owner_filter,))
            else:
                cursor.execute("""
                    SELECT owner_id, field_name, value, effective_confidence, updated_at
                    FROM active_preferences
                    ORDER BY owner_id, field_name
                """)

            rows = cursor.fetchall()

            if not rows:
                print("No active preferences found")
                return

            # Pretty print table
            print(f"\nActive Preferences ({len(rows)}):\n")
            print(f"{'Owner':<15} {'Field':<30} {'Value':<20} {'Confidence':<12} {'Updated':<20}")
            print("-" * 100)

            for row in rows:
                owner_id = row[0]
                field_name = row[1]
                value = row[2][:17] + "..." if len(row[2]) > 20 else row[2]
                confidence = f"{row[3]:.2f}"
                updated = row[4][:19] if row[4] else "N/A"

                print(f"{owner_id:<15} {field_name:<30} {value:<20} {confidence:<12} {updated:<20}")

    def preference_clear(self, args):
        """Clear (delete) a preference from active_preferences."""
        from circus.database import get_db

        owner = args.owner if args.owner else None
        field = args.field

        with get_db() as conn:
            cursor = conn.cursor()

            if owner:
                # Clear specific owner's preference
                cursor.execute("""
                    DELETE FROM active_preferences
                    WHERE owner_id = ? AND field_name = ?
                """, (owner, field))
            else:
                # Clear preference for all owners
                cursor.execute("""
                    DELETE FROM active_preferences
                    WHERE field_name = ?
                """, (field,))

            deleted = cursor.rowcount
            conn.commit()

            if deleted == 0:
                print(f"No preferences found for field '{field}'")
            else:
                print(f"✓ Cleared {deleted} preference(s) for field '{field}'")

    def preference_history(self, args):
        """Show preference change history from shared_memories audit trail."""
        from circus.database import get_db

        field_filter = args.field if args.field else None
        owner_filter = args.owner if args.owner else None

        with get_db() as conn:
            cursor = conn.cursor()

            # Build query with filters
            query = """
                SELECT id, from_agent_id, content, confidence, shared_at, provenance
                FROM shared_memories
                WHERE category = 'user_preference'
            """
            params = []

            if owner_filter:
                query += " AND json_extract(provenance, '$.owner_id') = ?"
                params.append(owner_filter)

            query += " ORDER BY shared_at DESC LIMIT 50"

            cursor.execute(query, params)
            rows = cursor.fetchall()

            if not rows:
                print("No preference history found")
                return

            # Parse and filter by field if specified
            import json
            filtered_rows = []

            for row in rows:
                try:
                    # Try to extract field from content (format varies)
                    provenance = json.loads(row[5]) if row[5] else {}
                    # Field info is in the memory content, not stored separately
                    # For now, show all if no field filter, or include if field_filter in content
                    if not field_filter or (field_filter in row[2]):
                        filtered_rows.append(row)
                except:
                    pass

            if not filtered_rows:
                print(f"No preference history found for field '{field_filter}'")
                return

            # Pretty print
            print(f"\nPreference History ({len(filtered_rows)} entries):\n")
            print(f"{'Memory ID':<20} {'Agent':<20} {'Confidence':<12} {'Shared At':<20}")
            print("-" * 80)

            for row in filtered_rows:
                mem_id = row[0][:17] + "..."
                agent_id = row[1][:17] + "..."
                confidence = f"{row[3]:.2f}"
                shared_at = row[4][:19]

                print(f"{mem_id:<20} {agent_id:<20} {confidence:<12} {shared_at:<20}")
                print(f"  Content: {row[2][:70]}...")
                print()

    def keys_list(self, args):
        """List owner keys (active + history)."""
        from circus.database import get_db

        owner_filter = args.owner if args.owner else None

        with get_db() as conn:
            cursor = conn.cursor()

            if owner_filter:
                cursor.execute("""
                    SELECT owner_id, public_key, created_at, is_active, rotated_at, revoked_at, revoked_reason
                    FROM owner_keys
                    WHERE owner_id = ?
                    ORDER BY created_at DESC
                """, (owner_filter,))
            else:
                cursor.execute("""
                    SELECT owner_id, public_key, created_at, is_active, rotated_at, revoked_at, revoked_reason
                    FROM owner_keys
                    ORDER BY owner_id, created_at DESC
                """)

            rows = cursor.fetchall()

            if not rows:
                print("No keys found")
                return

            # Pretty print
            print(f"\nOwner Keys ({len(rows)}):\n")
            print(f"{'Owner':<15} {'Public Key':<20} {'Created':<20} {'Status':<12} {'Updated':<20}")
            print("-" * 90)

            for row in rows:
                owner_id = row[0]
                public_key = row[1][:17] + "..."
                created = row[2][:19]
                is_active = row[3]
                rotated_at = row[4]
                revoked_at = row[5]
                revoked_reason = row[6]

                if is_active:
                    status = "ACTIVE"
                    updated = ""
                elif revoked_at:
                    status = f"REVOKED ({revoked_reason or 'unknown'})"
                    updated = revoked_at[:19]
                elif rotated_at:
                    status = "ROTATED"
                    updated = rotated_at[:19]
                else:
                    status = "INACTIVE"
                    updated = ""

                print(f"{owner_id:<15} {public_key:<20} {created:<20} {status:<12} {updated:<20}")

    def keys_events(self, args):
        """Show key events audit log."""
        from circus.database import get_db

        owner_filter = args.owner if args.owner else None

        with get_db() as conn:
            cursor = conn.cursor()

            if owner_filter:
                cursor.execute("""
                    SELECT id, owner_id, event_type, public_key_b64, previous_key_b64, reason, happened_at, actor
                    FROM key_events
                    WHERE owner_id = ?
                    ORDER BY happened_at DESC
                    LIMIT 50
                """, (owner_filter,))
            else:
                cursor.execute("""
                    SELECT id, owner_id, event_type, public_key_b64, previous_key_b64, reason, happened_at, actor
                    FROM key_events
                    ORDER BY happened_at DESC
                    LIMIT 50
                """)

            rows = cursor.fetchall()

            if not rows:
                print("No key events found")
                return

            # Pretty print
            print(f"\nKey Events ({len(rows)}):\n")
            print(f"{'Event ID':<20} {'Owner':<15} {'Type':<15} {'Happened':<20} {'Actor':<20}")
            print("-" * 95)

            for row in rows:
                event_id = row[0][:17] + "..."
                owner_id = row[1]
                event_type = row[2]
                happened = row[6][:19]
                actor = row[7] if row[7] else "N/A"
                actor_short = actor[:17] + "..." if len(actor) > 20 else actor

                print(f"{event_id:<20} {owner_id:<15} {event_type:<15} {happened:<20} {actor_short:<20}")

                # Show reason if present
                if row[5]:
                    print(f"  Reason: {row[5]}")

    def keys_revoke(self, args):
        """Revoke owner key (operator command)."""
        from circus.database import get_db

        owner = args.owner
        reason = args.reason if args.reason else "operator-revoke"

        with get_db() as conn:
            cursor = conn.cursor()
            now = datetime.utcnow().isoformat()

            # Fetch current active key
            cursor.execute("""
                SELECT public_key FROM owner_keys
                WHERE owner_id = ? AND is_active = 1
            """, (owner,))
            row = cursor.fetchone()

            if not row:
                print(f"Error: No active key found for owner '{owner}'")
                sys.exit(1)

            public_key_b64 = row[0]

            # Mark key as revoked
            cursor.execute("""
                UPDATE owner_keys
                SET is_active = 0,
                    revoked_at = ?,
                    revoked_reason = ?
                WHERE owner_id = ? AND public_key = ? AND is_active = 1
            """, (now, reason, owner, public_key_b64))

            # Log key_events entry
            import secrets
            event_id = f"kevent-{secrets.token_hex(8)}"
            cursor.execute("""
                INSERT INTO key_events (
                    id, owner_id, event_type, public_key_b64,
                    reason, happened_at, actor
                ) VALUES (?, ?, 'revoked', ?, ?, ?, 'operator')
            """, (event_id, owner, public_key_b64, reason, now))

            conn.commit()

            print(f"✓ Key revoked for owner '{owner}'")
            print(f"  Public key: {public_key_b64[:32]}...")
            print(f"  Reason: {reason}")
            print(f"  Event ID: {event_id}")

    def federation_peers(self, args):
        """List federation peers with health status."""
        response = self.client.get(f"{self.base_url}/api/v1/federation/peers")

        if response.status_code == 200:
            result = response.json()
            peers = result.get("peers", [])

            if not peers:
                print("No federation peers registered")
                return

            print(f"\nFederation Peers ({result['count']}):\n")
            print(f"{'URL':<40} {'Status':<12} {'Failures':<10} {'Last Seen':<20}")
            print("-" * 85)

            for peer in peers:
                url = peer["url"][:37] + "..." if len(peer["url"]) > 40 else peer["url"]
                status = "HEALTHY" if peer["is_healthy"] else "UNHEALTHY"
                failures = peer["consecutive_failures"]
                last_seen = peer["last_seen_at"][:19] if peer["last_seen_at"] else "Never"

                print(f"{url:<40} {status:<12} {failures:<10} {last_seen:<20}")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def federation_outbox(self, args):
        """List federation outbox entries."""
        params = {}
        if args.status:
            params["status"] = args.status

        response = self.client.get(f"{self.base_url}/api/v1/federation/outbox", params=params)

        if response.status_code == 200:
            result = response.json()
            entries = result.get("entries", [])

            if not entries:
                print("No outbox entries found")
                return

            print(f"\nFederation Outbox ({result['count']}):\n")
            print(f"{'ID':<20} {'Peer':<30} {'Status':<12} {'Attempts':<10} {'Created':<20}")
            print("-" * 95)

            for entry in entries:
                entry_id = entry["id"][:17] + "..."
                peer = entry["peer_url"][:27] + "..." if len(entry["peer_url"]) > 30 else entry["peer_url"]
                status = entry["status"].upper()
                attempts = entry["attempt_count"]
                created = entry["created_at"][:19]

                print(f"{entry_id:<20} {peer:<30} {status:<12} {attempts:<10} {created:<20}")

                if entry["error"]:
                    print(f"  Error: {entry['error'][:80]}")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def federation_metrics(self, args):
        """Show federation delivery metrics."""
        response = self.client.get(f"{self.base_url}/api/v1/federation/metrics")

        if response.status_code == 200:
            metrics = response.json()

            print("\nFederation Outbox Metrics:\n")
            print(f"  Pending:    {metrics['pending']:>6}")
            print(f"  Delivered:  {metrics['delivered']:>6}")
            print(f"  Failed:     {metrics['failed']:>6}")
            print(f"  Abandoned:  {metrics['abandoned']:>6}")
            print(f"  {'─' * 17}")
            print(f"  Total:      {metrics['total']:>6}")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def federation_add_peer(self, args):
        """Add a federation peer."""
        data = {"url": args.url}
        if args.name:
            data["name"] = args.name

        response = self.client.post(f"{self.base_url}/api/v1/federation/peers", json=data)

        if response.status_code == 200:
            result = response.json()
            print(f"✓ Federation peer added: {result['url']}")
            print(f"  Name: {result['name']}")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def governance_quarantine(self, args):
        """List quarantined memories."""
        params = {}
        if args.owner:
            params["owner_id"] = args.owner

        response = self.client.get(f"{self.base_url}/api/v1/governance/quarantine", params=params)

        if response.status_code == 200:
            result = response.json()
            entries = result.get("quarantined", [])

            if not entries:
                print("No quarantined memories found.")
                return

            print(f"\nQuarantined Memories ({result['count']}):\n")
            for entry in entries:
                print(f"ID: {entry['id']}")
                print(f"  Memory ID: {entry['memory_id']}")
                print(f"  Owner: {entry['owner_id']}")
                print(f"  Reason: {entry['reason']}")
                print(f"  Quarantined: {entry['quarantined_at']}")
                if entry.get('memory'):
                    mem = entry['memory']
                    print(f"  Content: {mem.get('content', '')[:80]}...")
                    print(f"  Category: {mem.get('category')}")
                print()
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def governance_release(self, args):
        """Release a quarantined memory."""
        data = {
            "admit": args.admit,
            "reason": args.reason or "Manual review passed"
        }

        response = self.client.post(
            f"{self.base_url}/api/v1/governance/quarantine/{args.quarantine_id}/release",
            json=data
        )

        if response.status_code == 200:
            result = response.json()
            print(f"✓ Released quarantine entry: {args.quarantine_id}")
            if result.get("admitted"):
                print("  Preference activated successfully")
            else:
                print("  Released without activation")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def governance_discard(self, args):
        """Discard a quarantined memory."""
        response = self.client.post(
            f"{self.base_url}/api/v1/governance/quarantine/{args.quarantine_id}/discard"
        )

        if response.status_code == 200:
            print(f"✓ Discarded quarantine entry: {args.quarantine_id}")
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)

    def governance_audit(self, args):
        """Show governance audit log."""
        params = {"limit": args.limit}
        if args.owner:
            params["owner_id"] = args.owner

        response = self.client.get(f"{self.base_url}/api/v1/governance/audit", params=params)

        if response.status_code == 200:
            result = response.json()
            events = result.get("events", [])

            if not events:
                print("No audit events found.")
                return

            print(f"\nGovernance Audit Log ({result['count']} events):\n")
            for event in events:
                print(f"[{event['happened_at']}] {event['event_type']}")
                print(f"  Actor: {event.get('actor', 'N/A')}")
                print(f"  Owner: {event.get('owner_id', 'N/A')}")
                if event.get('detail'):
                    print(f"  Detail: {json.dumps(event['detail'], indent=4)}")
                print()
        else:
            print(f"Error: {response.status_code} - {response.text}", file=sys.stderr)
            sys.exit(1)


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="The Circus - Agent Commons CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "--base-url",
        default=os.getenv("CIRCUS_BASE_URL", "http://localhost:6200"),
        help="Circus API base URL"
    )

    parser.add_argument(
        "--token",
        default=os.getenv("CIRCUS_TOKEN"),
        help="Ring token for authentication"
    )

    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # Generate passport command
    gen_passport_parser = subparsers.add_parser("generate-passport", help="Generate passport from AI-IQ database")
    gen_passport_parser.add_argument("--name", required=True, help="Agent name")
    gen_passport_parser.add_argument("--role", required=True, help="Agent role")
    gen_passport_parser.add_argument("--passport-db", required=True, help="Path to AI-IQ memories.db")
    gen_passport_parser.add_argument("--output", help="Output file path (default: ~/.circus/passport.json)")

    # Hull integrity command
    hull_parser = subparsers.add_parser("hull", help="Check agent hull integrity (token budget health)")
    hull_source = hull_parser.add_mutually_exclusive_group()
    hull_source.add_argument("--session", help="Path to Claude Code JSONL session file")
    hull_source.add_argument("--squadron", help="Path to session directory (scans flagship + subagents)")
    hull_parser.add_argument("--agent", dest="agent_name", help="Agent name (for --session mode)")
    hull_parser.add_argument("--tokens", type=int, help="Manual token count (skips file reading)")
    hull_parser.add_argument("--limit", type=int, default=200000, help="Token limit (default: 200000)")

    # Register command
    register_parser = subparsers.add_parser("register", help="Register a new agent")
    register_parser.add_argument("--name", required=True, help="Agent name")
    register_parser.add_argument("--role", required=True, help="Agent role")
    register_parser.add_argument("--capabilities", required=True, help="Comma-separated capabilities")
    register_parser.add_argument("--home", required=True, help="Home instance URL")
    register_parser.add_argument("--passport", help="Path to AI-IQ passport JSON")
    register_parser.add_argument("--passport-db", help="Path to AI-IQ memories.db (alternative to --passport)")
    register_parser.add_argument("--contact", help="Contact info")

    # Discover command
    discover_parser = subparsers.add_parser("discover", help="Discover agents")
    discover_parser.add_argument("--capability", help="Filter by capability")
    discover_parser.add_argument("--entity", help="Filter by entity")
    discover_parser.add_argument("--trait", help="Filter by trait")
    discover_parser.add_argument("--min-trust", type=float, default=30.0, help="Minimum trust score")

    # Join command
    join_parser = subparsers.add_parser("join", help="Join a room")
    join_parser.add_argument("room_slug", help="Room slug (e.g., #engineering)")
    join_parser.add_argument("--sync", action="store_true", help="Enable memory sync")

    # Share command
    share_parser = subparsers.add_parser("share", help="Share memory to room")
    share_parser.add_argument("room_slug", help="Room slug (e.g., #engineering)")
    share_parser.add_argument("content", help="Memory content")
    share_parser.add_argument("--category", help="Memory category")
    share_parser.add_argument("--project", help="Project name")
    share_parser.add_argument("--tags", help="Comma-separated tags")

    # Handshake command
    handshake_parser = subparsers.add_parser("handshake", help="Initiate handshake")
    handshake_parser.add_argument("target_agent_id", help="Target agent ID")
    handshake_parser.add_argument("--purpose", help="Purpose of handshake")

    # Rooms command
    rooms_parser = subparsers.add_parser("rooms", help="List available rooms")

    # Serve command
    serve_parser = subparsers.add_parser("serve", help="Start The Circus API server")
    serve_parser.add_argument("--host", default="0.0.0.0", help="Host to bind to")
    serve_parser.add_argument("--port", type=int, default=6200, help="Port to bind to")

    # Owner keygen command
    keygen_parser = subparsers.add_parser("owner-keygen", help="Generate owner keypair")
    keygen_parser.add_argument("--owner", required=True, help="Owner ID (e.g., 'kobus')")
    keygen_parser.add_argument("--output", required=True, help="Output path for private key (public key gets .pub suffix)")
    keygen_parser.add_argument("--description", help="Optional description")
    keygen_parser.add_argument("--force", action="store_true", help="Overwrite existing files")

    # Owner add command
    add_parser = subparsers.add_parser("owner-add", help="Import owner public key from file")
    add_parser.add_argument("--owner", required=True, help="Owner ID (e.g., 'kobus')")
    add_parser.add_argument("--public-key-file", required=True, help="Path to public key file")
    add_parser.add_argument("--description", help="Optional description")

    # Preference command (Week 6)
    preference_parser = subparsers.add_parser("preference", help="Preference inspector commands")
    preference_subparsers = preference_parser.add_subparsers(dest="preference_command", help="Preference subcommands")

    # preference list
    pref_list_parser = preference_subparsers.add_parser("list", help="List active preferences")
    pref_list_parser.add_argument("--owner", help="Filter by owner ID")

    # preference clear
    pref_clear_parser = preference_subparsers.add_parser("clear", help="Clear a preference")
    pref_clear_parser.add_argument("field", help="Preference field name to clear")
    pref_clear_parser.add_argument("--owner", help="Owner ID (if omitted, clears for all owners)")

    # preference history
    pref_history_parser = preference_subparsers.add_parser("history", help="Show preference history")
    pref_history_parser.add_argument("--field", help="Filter by field name")
    pref_history_parser.add_argument("--owner", help="Filter by owner ID")

    # Keys command (Week 9)
    keys_parser = subparsers.add_parser("keys", help="Owner key lifecycle commands")
    keys_subparsers = keys_parser.add_subparsers(dest="keys_command", help="Keys subcommands")

    # keys list
    keys_list_parser = keys_subparsers.add_parser("list", help="List owner keys")
    keys_list_parser.add_argument("--owner", help="Filter by owner ID")

    # keys events
    keys_events_parser = keys_subparsers.add_parser("events", help="Show key events audit log")
    keys_events_parser.add_argument("--owner", help="Filter by owner ID")

    # keys revoke
    keys_revoke_parser = keys_subparsers.add_parser("revoke", help="Revoke owner key")
    keys_revoke_parser.add_argument("--owner", required=True, help="Owner ID")
    keys_revoke_parser.add_argument("--reason", help="Revocation reason")

    # Federation command (W10)
    federation_parser = subparsers.add_parser("federation", help="Federation durability commands")
    federation_subparsers = federation_parser.add_subparsers(dest="federation_command", help="Federation subcommands")

    # federation peers
    fed_peers_parser = federation_subparsers.add_parser("peers", help="List federation peers with health status")

    # federation outbox
    fed_outbox_parser = federation_subparsers.add_parser("outbox", help="List outbox entries")
    fed_outbox_parser.add_argument("--status", choices=["pending", "delivered", "failed", "abandoned"], help="Filter by status")

    # federation metrics
    fed_metrics_parser = federation_subparsers.add_parser("metrics", help="Show delivery stats")

    # federation add-peer
    fed_add_peer_parser = federation_subparsers.add_parser("add-peer", help="Register a federation peer")
    fed_add_peer_parser.add_argument("url", help="Peer base URL (e.g., http://peer:6200)")
    fed_add_peer_parser.add_argument("--name", help="Optional human name")

    # Governance commands (W11)
    governance_parser = subparsers.add_parser("governance", help="Governance commands (quarantine + audit)")
    governance_subparsers = governance_parser.add_subparsers(dest="governance_command", help="Governance subcommands")

    # Quarantine list
    gov_quarantine_parser = governance_subparsers.add_parser("quarantine", help="List quarantined memories")
    gov_quarantine_parser.add_argument("--owner", help="Filter by owner ID")

    # Release from quarantine
    gov_release_parser = governance_subparsers.add_parser("release", help="Release quarantined memory")
    gov_release_parser.add_argument("quarantine_id", help="Quarantine entry ID")
    gov_release_parser.add_argument("--admit", action="store_true", help="Force-activate the preference")
    gov_release_parser.add_argument("--reason", help="Release reason")

    # Discard from quarantine
    gov_discard_parser = governance_subparsers.add_parser("discard", help="Discard quarantined memory")
    gov_discard_parser.add_argument("quarantine_id", help="Quarantine entry ID")

    # Audit log
    gov_audit_parser = governance_subparsers.add_parser("audit", help="Show governance audit log")
    gov_audit_parser.add_argument("--owner", help="Filter by owner ID")
    gov_audit_parser.add_argument("--limit", type=int, default=20, help="Max entries (default: 20)")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    # Initialize CLI
    cli = CircusCLI(base_url=args.base_url, token=args.token)

    # Execute command
    if args.command == "generate-passport":
        cli.generate_passport(args)
    elif args.command == "register":
        cli.register(args)
    elif args.command == "discover":
        cli.discover(args)
    elif args.command == "join":
        cli.join(args)
    elif args.command == "share":
        cli.share(args)
    elif args.command == "handshake":
        cli.handshake(args)
    elif args.command == "rooms":
        cli.rooms(args)
    elif args.command == "serve":
        cli.serve(args)
    elif args.command == "owner-keygen":
        cli.owner_keygen(args)
    elif args.command == "owner-add":
        cli.owner_add(args)
    elif args.command == "preference":
        if not hasattr(args, 'preference_command') or not args.preference_command:
            print("Usage: circus preference {list|clear|history} [options]", file=sys.stderr)
            sys.exit(1)
        elif args.preference_command == "list":
            cli.preference_list(args)
        elif args.preference_command == "clear":
            cli.preference_clear(args)
        elif args.preference_command == "history":
            cli.preference_history(args)
        else:
            print("Unknown preference subcommand", file=sys.stderr)
            sys.exit(1)
    elif args.command == "keys":
        if not hasattr(args, 'keys_command') or not args.keys_command:
            print("Usage: circus keys {list|events|revoke} [options]", file=sys.stderr)
            sys.exit(1)
        elif args.keys_command == "list":
            cli.keys_list(args)
        elif args.keys_command == "events":
            cli.keys_events(args)
        elif args.keys_command == "revoke":
            cli.keys_revoke(args)
        else:
            print("Unknown keys subcommand", file=sys.stderr)
            sys.exit(1)
    elif args.command == "federation":
        if not hasattr(args, 'federation_command') or not args.federation_command:
            print("Usage: circus federation {peers|outbox|metrics|add-peer} [options]", file=sys.stderr)
            sys.exit(1)
        elif args.federation_command == "peers":
            cli.federation_peers(args)
        elif args.federation_command == "outbox":
            cli.federation_outbox(args)
        elif args.federation_command == "metrics":
            cli.federation_metrics(args)
        elif args.federation_command == "add-peer":
            cli.federation_add_peer(args)
        else:
            print("Unknown federation subcommand", file=sys.stderr)
            sys.exit(1)
    elif args.command == "governance":
        if not hasattr(args, 'governance_command') or not args.governance_command:
            print("Usage: circus governance {quarantine|release|discard|audit} [options]", file=sys.stderr)
            sys.exit(1)
        elif args.governance_command == "quarantine":
            cli.governance_quarantine(args)
        elif args.governance_command == "release":
            cli.governance_release(args)
        elif args.governance_command == "discard":
            cli.governance_discard(args)
        elif args.governance_command == "audit":
            cli.governance_audit(args)
        else:
            print("Unknown governance subcommand", file=sys.stderr)
            sys.exit(1)
    elif args.command == "hull":
        from circus.services.hull_integrity import (
            check_session, scan_session_dir, readiness_board, build_report
        )
        import json as _json
        if hasattr(args, "squadron") and args.squadron:
            reports = scan_session_dir(args.squadron, args.limit)
            if not reports:
                print("No JSONL session data found.", file=sys.stderr)
                sys.exit(1)
            print(readiness_board(reports))
            print(_json.dumps(reports, indent=2))
        elif hasattr(args, "session") and args.session:
            name = getattr(args, "agent_name", None) or "Agent"
            report = check_session(args.session, agent_name=name, token_limit=args.limit)
            if not report:
                print("No token usage data in session file.", file=sys.stderr)
                sys.exit(1)
            print(readiness_board([report]))
            print(_json.dumps(report, indent=2))
        elif hasattr(args, "tokens") and args.tokens is not None:
            name = getattr(args, "agent_name", None) or "Agent"
            report = build_report(name, args.tokens, args.limit)
            print(readiness_board([report]))
            print(_json.dumps(report, indent=2))
        else:
            print("Usage: circus hull --session <path> | --squadron <dir> | --agent <name> --tokens <N>")
            sys.exit(1)


if __name__ == "__main__":
    main()
